name: Deploy VM with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        run: |
          az login --identity || az login --use-device-code
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ${{ github.workspace }}/terraform

      - name: Plan Terraform Deployment
        run: terraform plan
        working-directory: ${{ github.workspace }}/terraform

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve
        working-directory: ${{ github.workspace }}/terraform